server:
  port: 8769                    # 指定该Eureka实例的端口
spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false