server:
  port: 8084
fdfs:
  so-timeout: 1500 #socket连接超时时长
  connect-timeout: 600 #连接tracker服务器超时时长
  res-host: 119.27.166.15
  storage-port: 23000
  tracker-list: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 119.27.166.15:22122
spring:
  jackson:
    default-property-inclusion: non_null  #jackson实体转json时,属性为null不参加序列化
