server:
  port: 8084
spring:
  application:
    name: mini-program-shop-common
  rabbitmq:
    host: 119.27.166.15
    port: 5672
    username: Iason
    password: wwy383059893
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
fdfs:
  so-timeout: 1500 #socket连接超时时长
  connect-timeout: 600 #连接tracker服务器超时时长
  res-host: 119.27.166.15
  storage-port: 23000
  tracker-list: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 119.27.166.15:22122
